name: python example

on:
   workflow_dispatch:
     inputs:
       path_to_fileInput:
         description: 'Enter the path to file'
         required: true
         default: "/home/runner/work/forma/forma/forma.json"


jobs:
  execute_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Execute Test Script
        run: |
          echo "Store: ${{ github.event.inputs.path_to_fileInput }}"
          PATH_TO_FILE=${{ github.event.inputs.path_to_fileInput }} python3 main.py