on: push

jobs:
  execute_python:
	runs-on: ubuntu-latest
	container:
		image: python:alpine3.17
	- name: Checkout
  	  uses: actions/checkout@v3
  	  with:
	name: json parsing
	steps:
	  run: |
	    echo "executing python"

